"""Plugin discovery, registry, and SDK primitives."""

from .builtin import (
    COMET_PLUGIN_NAME,
    LISTRR_PLUGIN_NAME,
    MDBLIST_PLUGIN_NAME,
    NOTIFICATIONS_PLUGIN_NAME,
    PLEX_PLUGIN_NAME,
    PROWLARR_PLUGIN_NAME,
    RARBG_PLUGIN_NAME,
    SEERR_PLUGIN_NAME,
    STREAM_CONTROL_PLUGIN_NAME,
    STREMTHRU_PLUGIN_NAME,
    TORRENTIO_PLUGIN_NAME,
    CometScraper,
    HostStreamControlPlugin,
    ListrrContentService,
    MDBListContentService,
    PlexLibraryRefreshPlugin,
    ProwlarrScraper,
    RarbgScraper,
    SeerrContentService,
    StremThruDownloader,
    TorrentioScraper,
    WebhookNotificationPlugin,
)
from .builtins import register_builtin_plugins
from .context import HostPluginDatasource, PluginContext, PluginContextProvider
from .hooks import PluginHookWorkerExecutor
from .interfaces import (
    ContentRequest,
    ContentServicePlugin,
    DownloaderPlugin,
    DownloadFileRecord,
    DownloadLinkResult,
    DownloadLinksInput,
    DownloadStatusInput,
    DownloadStatusResult,
    ExternalIdentifiers,
    IndexerInput,
    IndexerPlugin,
    IndexerResult,
    MagnetAddInput,
    MagnetAddResult,
    NotificationEvent,
    NotificationPlugin,
    PluginDatasource,
    PluginEventHookWorker,
    ScraperPlugin,
    ScraperResult,
    ScraperSearchInput,
    StreamControlAction,
    StreamControlInput,
    StreamControlPlugin,
    StreamControlResult,
)
from .loader import (
    PluginLoadFailure,
    PluginLoadReport,
    PluginLoadSuccess,
    PluginRuntimePolicy,
    load_graphql_plugins,
    load_plugins,
)
from .manifest import GraphQLResolverExports, PluginManifest
from .registry import PluginCapabilityKind, PluginCapabilityRegistration, PluginRegistry
from .settings import PluginSettingsRegistry
from .testing import TestPluginContext

__all__ = [
    "MDBLIST_PLUGIN_NAME",
    "COMET_PLUGIN_NAME",
    "LISTRR_PLUGIN_NAME",
    "NOTIFICATIONS_PLUGIN_NAME",
    "PLEX_PLUGIN_NAME",
    "PROWLARR_PLUGIN_NAME",
    "RARBG_PLUGIN_NAME",
    "SEERR_PLUGIN_NAME",
    "STREAM_CONTROL_PLUGIN_NAME",
    "STREMTHRU_PLUGIN_NAME",
    "TORRENTIO_PLUGIN_NAME",
    "CometScraper",
    "ContentRequest",
    "ContentServicePlugin",
    "DownloadFileRecord",
    "DownloadLinkResult",
    "DownloadLinksInput",
    "DownloadStatusInput",
    "DownloadStatusResult",
    "DownloaderPlugin",
    "ExternalIdentifiers",
    "GraphQLResolverExports",
    "HostPluginDatasource",
    "HostStreamControlPlugin",
    "IndexerInput",
    "IndexerPlugin",
    "IndexerResult",
    "ListrrContentService",
    "MDBListContentService",
    "MagnetAddInput",
    "MagnetAddResult",
    "NotificationEvent",
    "NotificationPlugin",
    "PlexLibraryRefreshPlugin",
    "PluginCapabilityKind",
    "PluginCapabilityRegistration",
    "PluginContext",
    "PluginContextProvider",
    "PluginDatasource",
    "PluginEventHookWorker",
    "PluginHookWorkerExecutor",
    "PluginLoadFailure",
    "PluginLoadReport",
    "PluginLoadSuccess",
    "PluginManifest",
    "PluginRegistry",
    "PluginRuntimePolicy",
    "PluginSettingsRegistry",
    "ProwlarrScraper",
    "RarbgScraper",
    "SeerrContentService",
    "ScraperPlugin",
    "ScraperResult",
    "ScraperSearchInput",
    "StreamControlAction",
    "StreamControlInput",
    "StreamControlPlugin",
    "StreamControlResult",
    "StremThruDownloader",
    "TestPluginContext",
    "TorrentioScraper",
    "WebhookNotificationPlugin",
    "load_graphql_plugins",
    "load_plugins",
    "register_builtin_plugins",
]
